runtime: php72 # language of the app

runtime_config:
  document_root: public

env_variables:
  #  LOG_CHANNEL: stackdriver
  ## Put production environment variables here.
  APP_ENV: local   # or production
  APP_DEBUG: true # or false
  APP_KEY: base64:hvB8kB4JhTxm4BaN4QyLcEj7jZty/zVCcB6GdnXKguc=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  APP_TIMEZONE: Asia/Jakarta #your timezone of choice
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_DATABASE: apomade
  DB_USERNAME: root
  DB_PASSWORD: siswanto123321
  DB_SOCKET: "/cloudsql/apomade:asia-southeast1:teguhsiswanto87"
