runtime: php72

#runtime_config:
#  document_root: public

env_variables:
  #  LOG_CHANNEL: stackdriver
  ## Put production environment variables here.
  APP_KEY: base64:hvB8kB4JhTxm4BaN4QyLcEj7jZty/zVCcB6GdnXKguc=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
#  CACHE_DRIVER: database
  SESSION_DRIVER: cookie
  ## Set these environment variables according to your CloudSQL configuration.
#  DB_DATABASE: apomade
#  DB_USERNAME: root
#  DB_PASSWORD: siswanto123321
#  DB_SOCKET: "/cloudsql/apomade:asia-southeast1:teguhsiswanto87"
