runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:nluWQHejOcdhkeAN1bY9x9deqOLxHMcN2qNci5qVr7c=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
